---
- name: Main | import common tasks
  ansible.builtin.import_tasks: "common.yml"

- name: Main | include os specific tasks
  ansible.builtin.include_tasks: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "."

- name: Main | include pre-check tasks
  include_tasks: "pre_check.yml"

- name: Main | create temporary certificate directory
  file:
    path: "{{ vencrypt_dir }}"
    state: directory
    mode: "0700"

- name: Main | include VeNCrypt tasks
  include_tasks: "vencrypt.yml"

- name: Main | include vnc_secret tasks
  include_tasks: "vnc_secret.yml"

- name: Main | remove temporary certificate directory
  file:
    path: "{{ vencrypt_dir }}"
    state: absent
...
