---
- name: VNC Secret | check if vnc server secret exists
  command: >-
    {{ kubectl_cmd }} get secret vnc-server-secret -n openstack
  become: true
  register: get_secret
  failed_when: get_secret.rc not in [0, 1]

- name: VNC Secret | create vnc server secret
  command: >-
    {{ kubectl_cmd }} create secret generic vnc-server-secret \
      --from-file=ca_crt={{ vencrypt_ca.crt }} \
      --from-file=server_crt={{ vencrypt_server.crt }} \
      --from-file=server_key={{ vencrypt_server.key }} \
      -n openstack
  become: true
  when: get_secret.rc != 0

- name: VNC Secret | check if vnc client secret exists
  command: >-
    {{ kubectl_cmd }} get secret vnc-client-secret -n openstack
  become: true
  register: get_secret
  failed_when: get_secret.rc not in [0, 1]

- name: VNC Secret | create vnc client secret
  command: >-
    {{ kubectl_cmd }} create secret generic vnc-client-secret \
      --from-file=ca_crt={{ vencrypt_ca.crt }} \
      --from-file=client_crt={{ vencrypt_client.crt }} \
      --from-file=client_key={{ vencrypt_client.key }} \
      -n openstack
  become: true
  when: get_secret.rc != 0
...
